"""
Priority Improvement Generator
------------------------------

Converts the existing ATS + AI analysis into a small list of
high-value, actionable resume improvements.

Important:
This service does NOT call an LLM.

It uses information that has already been generated by:
    - ATS scorer
    - AI analyzer
    - Resume structure analyzer

This keeps the results consistent and avoids another AI request.
"""


def generate_priority_improvements(
    ats_result: dict,
    ai_result: dict,
    resume_result: dict,
) -> list[dict]:
    """
    Generate ranked improvements for the resume.

    The function returns a list that matches the frontend
    PriorityImprovement TypeScript interface.
    """

    improvements: list[dict] = []

    # ---------------------------------------------------------
    # 1. Missing keywords / skills
    # ---------------------------------------------------------

    missing_keywords = ats_result.get(
        "missing_keywords",
        [],
    )

    if missing_keywords:
        # Limit the displayed keywords so the card doesn't
        # become unnecessarily large.
        keywords = missing_keywords[:6]

        improvements.append(
            {
                "id": "missing-keywords",
                "priority": 1,
                "title": "Strengthen relevant technical skills",
                "description": (
                    "Your resume is missing several keywords "
                    "that are relevant to the target role."
                ),
                "severity": "high",
                "related_keywords": keywords,
                "related_sections": [
                    "skills",
                    "experience",
                    "projects",
                ],
            }
        )

    # ---------------------------------------------------------
    # 2. Weak experience / achievements
    # ---------------------------------------------------------

    breakdown = ats_result.get(
        "breakdown",
        {},
    )

    experience_score = breakdown.get(
        "experience_achievements",
        20,
    )

    if experience_score < 12:
        improvements.append(
            {
                "id": "experience-description",
                "priority": len(improvements) + 1,
                "title": "Strengthen experience descriptions",
                "description": (
                    "Add clearer responsibilities, technologies, "
                    "and measurable results to your experience."
                ),
                "severity": "high",
                "related_keywords": [],
                "related_sections": [
                    "experience",
                ],
            }
        )

    # ---------------------------------------------------------
    # 3. Weak project descriptions
    # ---------------------------------------------------------

    projects = resume_result.get(
        "projects",
        [],
    )

    weak_projects = []

    for project in projects:
        responsibilities = project.get(
            "responsibilities",
            [],
        )

        achievements = project.get(
            "achievements",
            [],
        )

        # A project without responsibilities or achievements
        # usually needs more detail.
        if not responsibilities or not achievements:
            weak_projects.append(
                project.get("name", "Project")
            )

    if weak_projects:
        improvements.append(
            {
                "id": "project-description",
                "priority": len(improvements) + 1,
                "title": "Strengthen project descriptions",
                "description": (
                    "Add technical implementation details, "
                    "architecture, APIs, databases, and measurable "
                    "outcomes where applicable."
                ),
                "severity": "medium",
                "related_keywords": [],
                "related_sections": [
                    "projects",
                ],
            }
        )

    # ---------------------------------------------------------
    # 4. Missing information
    # ---------------------------------------------------------

    missing_information = ai_result.get(
        "missing_information",
        [],
    )

    if missing_information:
        improvements.append(
            {
                "id": "missing-information",
                "priority": len(improvements) + 1,
                "title": "Add missing resume information",
                "description": (
                    "Some potentially useful information was not "
                    "found in the resume."
                ),
                "severity": "medium",
                "related_keywords": [],
                "related_sections": [
                    "resume",
                ],
            }
        )

    # ---------------------------------------------------------
    # 5. Weak ATS structure
    # ---------------------------------------------------------

    structure_score = breakdown.get(
        "section_structure",
        20,
    )

    if structure_score < 15:
        improvements.append(
            {
                "id": "resume-structure",
                "priority": len(improvements) + 1,
                "title": "Improve resume structure",
                "description": (
                    "Use clear, standard resume sections and "
                    "consistent formatting to improve ATS parsing."
                ),
                "severity": "medium",
                "related_keywords": [],
                "related_sections": [
                    "resume",
                ],
            }
        )

    # ---------------------------------------------------------
    # Re-number priorities
    # ---------------------------------------------------------
    #
    # The conditions above may or may not add an improvement.
    # Re-number them at the end so priorities are always:
    #
    # 1, 2, 3, 4...
    #
    # rather than potentially skipping numbers.
    # ---------------------------------------------------------

    for index, improvement in enumerate(
        improvements,
        start=1,
    ):
        improvement["priority"] = index

    # ---------------------------------------------------------
    # Limit the number of improvements shown on the Results page
    # ---------------------------------------------------------

    return improvements[:5]
